
name: 'lol_data_engineering_pipeline'
version: '1.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  lol_data_engineering_pipeline:
    +materialized: view
    staging:
      +materialized: table
    core:
      +materialized: incremental
      +incremental_strategy: merge
      +unique_key: gameId